import type { Metadata } from 'next';
import './globals.css';
import EnvBanner from '@/components/core/banners/env-banner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <EnvBanner />
      {children}
    </html>
  );
}
