export const tKeys = {
  common: {
    errors: {
      required: 'common.errors.required',
    },
    back: 'common.back',
  },
  navbar: {
    home: 'navbar.home',
  },
  homepage: {
    title: 'homepage.title',
  },
  login: {
    title: 'login.title',
    emailLabel: 'login.emailLabel',
    passwordLabel: 'login.passwordLabel',
    submit: 'login.submit',
    emailInvalid: 'login.emailInvalid',
    invalidCredentials: 'login.invalidCredentials',
  },
  dashboard: {
    title: 'dashboard.title',
    welcome: 'dashboard.welcome',
    role: 'dashboard.role',
    noRole: 'dashboard.noRole',
    logout: 'dashboard.logout',
  },
  sidebar: {
    nav: {
      dashboard: 'sidebar.nav.dashboard',
      users: 'sidebar.nav.users',
      analytics: 'sidebar.nav.analytics',
      annonces: 'sidebar.nav.annonces',
      journal: 'sidebar.nav.journal',
      settings: 'sidebar.nav.settings',
    },
    comingSoon: 'sidebar.comingSoon',
    featureLocked: 'sidebar.featureLocked',
    menu: 'sidebar.menu',
    collapse: 'sidebar.collapse',
    expand: 'sidebar.expand',
  },
  users: {
    title: 'users.title',
    accessDenied: 'users.accessDenied',
    addButton: 'users.addButton',
    loadError: 'users.loadError',
    searchPlaceholder: 'users.searchPlaceholder',
    sort: {
      label: 'users.sort.label',
      default: 'users.sort.default',
      ascending: 'users.sort.ascending',
      descending: 'users.sort.descending',
    },
    empty: {
      createButton: 'users.empty.createButton',
      noResults: 'users.empty.noResults',
    },
    columns: {
      email: 'users.columns.email',
      name: 'users.columns.name',
      role: 'users.columns.role',
      status: 'users.columns.status',
      active: 'users.columns.active',
      inactive: 'users.columns.inactive',
    },
    create: {
      title: 'users.create.title',
      submit: 'users.create.submit',
      successTitle: 'users.create.successTitle',
      temporaryPasswordLabel: 'users.create.temporaryPasswordLabel',
      copy: 'users.create.copy',
      copied: 'users.create.copied',
      viewUser: 'users.create.viewUser',
      createError: 'users.create.createError',
    },
    detail: {
      header: 'users.detail.header',
      identityTitle: 'users.detail.identityTitle',
      roleTitle: 'users.detail.roleTitle',
      firstNameLabel: 'users.detail.firstNameLabel',
      lastNameLabel: 'users.detail.lastNameLabel',
      emailLabel: 'users.detail.emailLabel',
      notProvided: 'users.detail.notProvided',
      createdAt: 'users.detail.createdAt',
      lastSignIn: 'users.detail.lastSignIn',
      neverSignedIn: 'users.detail.neverSignedIn',
      active: 'users.detail.active',
      inactive: 'users.detail.inactive',
      loadError: 'users.detail.loadError',
      roles: {
        admin: {
          label: 'users.detail.roles.admin.label',
          description: 'users.detail.roles.admin.description',
        },
        manager: {
          label: 'users.detail.roles.manager.label',
          description: 'users.detail.roles.manager.description',
        },
        user: {
          label: 'users.detail.roles.user.label',
          description: 'users.detail.roles.user.description',
        },
      },
      save: 'users.detail.save',
      saveSuccess: 'users.detail.saveSuccess',
      saveError: 'users.detail.saveError',
      cannotChangeOwnRole: 'users.detail.cannotChangeOwnRole',
      resetPassword: 'users.detail.resetPassword',
      resetPasswordSuccess: 'users.detail.resetPasswordSuccess',
      resetPasswordError: 'users.detail.resetPasswordError',
      deactivate: 'users.detail.deactivate',
      reactivate: 'users.detail.reactivate',
      deactivateConfirm: 'users.detail.deactivateConfirm',
      statusSuccess: 'users.detail.statusSuccess',
      statusError: 'users.detail.statusError',
      cannotDeactivateOwnAccount: 'users.detail.cannotDeactivateOwnAccount',
      delete: 'users.detail.delete',
      deleteConfirmTitle: 'users.detail.deleteConfirmTitle',
      deleteConfirmDescription: 'users.detail.deleteConfirmDescription',
      deleteConfirmPlaceholder: 'users.detail.deleteConfirmPlaceholder',
      deleteConfirmButton: 'users.detail.deleteConfirmButton',
      deleteCancel: 'users.detail.deleteCancel',
      deleteSuccess: 'users.detail.deleteSuccess',
      deleteError: 'users.detail.deleteError',
      cannotDeleteOwnAccount: 'users.detail.cannotDeleteOwnAccount',
      editButton: 'users.detail.editButton',
      editTitle: 'users.detail.editTitle',
      tabs: {
        info: 'users.detail.tabs.info',
        history: 'users.detail.tabs.history',
        logs: 'users.detail.tabs.logs',
      },
    },
  },
  resetPassword: {
    title: 'resetPassword.title',
    newPasswordLabel: 'resetPassword.newPasswordLabel',
    submit: 'resetPassword.submit',
    invalidLink: 'resetPassword.invalidLink',
    success: 'resetPassword.success',
    error: 'resetPassword.error',
  },
  pagination: {
    previous: 'pagination.previous',
    next: 'pagination.next',
    pageOf: 'pagination.pageOf',
  },
  settings: {
    title: 'settings.title',
    language: {
      label: 'settings.language.label',
      description: 'settings.language.description',
      options: {
        fr: 'settings.language.options.fr',
        en: 'settings.language.options.en',
      },
    },
    theme: {
      label: 'settings.theme.label',
      description: 'settings.theme.description',
      options: {
        light: 'settings.theme.options.light',
        dark: 'settings.theme.options.dark',
        system: 'settings.theme.options.system',
      },
    },
    updateError: 'settings.updateError',
  },
  analytics: {
    title: 'analytics.title',
    periodSelector: {
      days7: 'analytics.periodSelector.days7',
      days30: 'analytics.periodSelector.days30',
      days90: 'analytics.periodSelector.days90',
    },
    comparedToPreviousPeriod: 'analytics.comparedToPreviousPeriod',
    stats: {
      visitors: 'analytics.stats.visitors',
      pageviews: 'analytics.stats.pageviews',
    },
    chart: {
      title: 'analytics.chart.title',
    },
    panels: {
      pages: 'analytics.panels.pages',
      referrers: 'analytics.panels.referrers',
      countries: 'analytics.panels.countries',
      devices: 'analytics.panels.devices',
      os: 'analytics.panels.os',
    },
    direct: 'analytics.direct',
    loadError: 'analytics.loadError',
    noData: 'analytics.noData',
  },
  upgrade: {
    title: 'upgrade.title',
    body: 'upgrade.body',
    contactButton: 'upgrade.contactButton',
    features: {
      analytics: {
        body: 'upgrade.features.analytics.body',
      },
      banner: {
        body: 'upgrade.features.banner.body',
      },
    },
  },
  announcements: {
    title: 'announcements.title',
    accessDenied: 'announcements.accessDenied',
    loadError: 'announcements.loadError',
    addButton: 'announcements.addButton',
    emptyTitle: 'announcements.emptyTitle',
    emptyDescription: 'announcements.emptyDescription',
    columns: {
      message: 'announcements.columns.message',
      period: 'announcements.columns.period',
      status: 'announcements.columns.status',
      actions: 'announcements.columns.actions',
    },
    status: {
      live: 'announcements.status.live',
      scheduled: 'announcements.status.scheduled',
      expired: 'announcements.status.expired',
      disabled: 'announcements.status.disabled',
      pending: 'announcements.status.pending',
    },
    period: {
      unlimited: 'announcements.period.unlimited',
      from: 'announcements.period.from',
      until: 'announcements.period.until',
      range: 'announcements.period.range',
    },
    form: {
      createTitle: 'announcements.form.createTitle',
      editTitle: 'announcements.form.editTitle',
      messageLabel: 'announcements.form.messageLabel',
      messageCounter: 'announcements.form.messageCounter',
      linkUrlLabel: 'announcements.form.linkUrlLabel',
      linkLabelLabel: 'announcements.form.linkLabelLabel',
      variantLabel: 'announcements.form.variantLabel',
      variant: {
        info: 'announcements.form.variant.info',
        promo: 'announcements.form.variant.promo',
        alerte: 'announcements.form.variant.alerte',
      },
      startsAtLabel: 'announcements.form.startsAtLabel',
      endsAtLabel: 'announcements.form.endsAtLabel',
      dateHelp: 'announcements.form.dateHelp',
      isActiveLabel: 'announcements.form.isActiveLabel',
      previewTitle: 'announcements.form.previewTitle',
      submitCreate: 'announcements.form.submitCreate',
      submitEdit: 'announcements.form.submitEdit',
      createSuccess: 'announcements.form.createSuccess',
      saveSuccess: 'announcements.form.saveSuccess',
      errors: {
        forbidden: 'announcements.form.errors.forbidden',
        feature_disabled: 'announcements.form.errors.feature_disabled',
        message_required: 'announcements.form.errors.message_required',
        message_too_long: 'announcements.form.errors.message_too_long',
        link_url_invalid: 'announcements.form.errors.link_url_invalid',
        link_pair_required: 'announcements.form.errors.link_pair_required',
        link_label_length: 'announcements.form.errors.link_label_length',
        end_before_start: 'announcements.form.errors.end_before_start',
        unexpected_error: 'announcements.form.errors.unexpected_error',
      },
    },
    toggleOn: 'announcements.toggleOn',
    toggleOff: 'announcements.toggleOff',
    deleteConfirmTitle: 'announcements.deleteConfirmTitle',
    deleteConfirmDescription: 'announcements.deleteConfirmDescription',
    deleteConfirmButton: 'announcements.deleteConfirmButton',
    deleteCancel: 'announcements.deleteCancel',
    deleteSuccess: 'announcements.deleteSuccess',
    deleteError: 'announcements.deleteError',
    toggleError: 'announcements.toggleError',
    public: {
      ariaLabel: 'announcements.public.ariaLabel',
      dismissAriaLabel: 'announcements.public.dismissAriaLabel',
    },
    detail: {
      loadError: 'announcements.detail.loadError',
      tabs: {
        edit: 'announcements.detail.tabs.edit',
        history: 'announcements.detail.tabs.history',
      },
    },
  },
  journal: {
    title: 'journal.title',
    accessDenied: 'journal.accessDenied',
    loadError: 'journal.loadError',
    empty: 'journal.empty',
    system: 'journal.system',
    columns: {
      date: 'journal.columns.date',
      user: 'journal.columns.user',
      action: 'journal.columns.action',
      type: 'journal.columns.type',
      element: 'journal.columns.element',
      details: 'journal.columns.details',
    },
    actions: {
      insert: 'journal.actions.insert',
      update: 'journal.actions.update',
      delete: 'journal.actions.delete',
      restore: 'journal.actions.restore',
    },
    filters: {
      user: 'journal.filters.user',
      allUsers: 'journal.filters.allUsers',
      system: 'journal.filters.system',
      type: 'journal.filters.type',
      allTypes: 'journal.filters.allTypes',
      action: 'journal.filters.action',
      allActions: 'journal.filters.allActions',
      from: 'journal.filters.from',
      to: 'journal.filters.to',
      reset: 'journal.filters.reset',
    },
    models: {
      announcements: 'journal.models.announcements',
      users: 'journal.models.users',
    },
    diff: {
      seeMore: 'journal.diff.seeMore',
      seeLess: 'journal.diff.seeLess',
      createdValues: 'journal.diff.createdValues',
      deletedValues: 'journal.diff.deletedValues',
    },
    detailsPanel: {
      title: 'journal.detailsPanel.title',
      close: 'journal.detailsPanel.close',
    },
    history: {
      empty: 'journal.history.empty',
      loadError: 'journal.history.loadError',
    },
  },
} as const;
