export const tKeys = {
  common: {
    errors: {
      required: 'common.errors.required',
    },
    back: 'common.back',
  },
  navbar: {
    home: 'navbar.home',
  },
  homepage: {
    title: 'homepage.title',
  },
  login: {
    title: 'login.title',
    emailLabel: 'login.emailLabel',
    passwordLabel: 'login.passwordLabel',
    submit: 'login.submit',
    emailInvalid: 'login.emailInvalid',
    invalidCredentials: 'login.invalidCredentials',
  },
  dashboard: {
    title: 'dashboard.title',
    welcome: 'dashboard.welcome',
    role: 'dashboard.role',
    noRole: 'dashboard.noRole',
    logout: 'dashboard.logout',
  },
  sidebar: {
    nav: {
      dashboard: 'sidebar.nav.dashboard',
      users: 'sidebar.nav.users',
      settings: 'sidebar.nav.settings',
    },
    comingSoon: 'sidebar.comingSoon',
    menu: 'sidebar.menu',
    collapse: 'sidebar.collapse',
    expand: 'sidebar.expand',
  },
  users: {
    title: 'users.title',
    accessDenied: 'users.accessDenied',
    addButton: 'users.addButton',
    loadError: 'users.loadError',
    columns: {
      email: 'users.columns.email',
      name: 'users.columns.name',
      role: 'users.columns.role',
      status: 'users.columns.status',
      active: 'users.columns.active',
      inactive: 'users.columns.inactive',
    },
    create: {
      title: 'users.create.title',
      submit: 'users.create.submit',
      successTitle: 'users.create.successTitle',
      temporaryPasswordLabel: 'users.create.temporaryPasswordLabel',
      copy: 'users.create.copy',
      copied: 'users.create.copied',
      viewUser: 'users.create.viewUser',
      createError: 'users.create.createError',
    },
    detail: {
      header: 'users.detail.header',
      identityTitle: 'users.detail.identityTitle',
      roleTitle: 'users.detail.roleTitle',
      firstNameLabel: 'users.detail.firstNameLabel',
      lastNameLabel: 'users.detail.lastNameLabel',
      emailLabel: 'users.detail.emailLabel',
      notProvided: 'users.detail.notProvided',
      createdAt: 'users.detail.createdAt',
      lastSignIn: 'users.detail.lastSignIn',
      neverSignedIn: 'users.detail.neverSignedIn',
      active: 'users.detail.active',
      inactive: 'users.detail.inactive',
      loadError: 'users.detail.loadError',
      roles: {
        admin: {
          label: 'users.detail.roles.admin.label',
          description: 'users.detail.roles.admin.description',
        },
        manager: {
          label: 'users.detail.roles.manager.label',
          description: 'users.detail.roles.manager.description',
        },
        user: {
          label: 'users.detail.roles.user.label',
          description: 'users.detail.roles.user.description',
        },
      },
      save: 'users.detail.save',
      saveSuccess: 'users.detail.saveSuccess',
      saveError: 'users.detail.saveError',
      cannotChangeOwnRole: 'users.detail.cannotChangeOwnRole',
      resetPassword: 'users.detail.resetPassword',
      resetPasswordSuccess: 'users.detail.resetPasswordSuccess',
      resetPasswordError: 'users.detail.resetPasswordError',
      deactivate: 'users.detail.deactivate',
      reactivate: 'users.detail.reactivate',
      deactivateConfirm: 'users.detail.deactivateConfirm',
      statusSuccess: 'users.detail.statusSuccess',
      statusError: 'users.detail.statusError',
      cannotDeactivateOwnAccount: 'users.detail.cannotDeactivateOwnAccount',
      delete: 'users.detail.delete',
      deleteConfirmTitle: 'users.detail.deleteConfirmTitle',
      deleteConfirmDescription: 'users.detail.deleteConfirmDescription',
      deleteConfirmPlaceholder: 'users.detail.deleteConfirmPlaceholder',
      deleteConfirmButton: 'users.detail.deleteConfirmButton',
      deleteCancel: 'users.detail.deleteCancel',
      deleteSuccess: 'users.detail.deleteSuccess',
      deleteError: 'users.detail.deleteError',
      cannotDeleteOwnAccount: 'users.detail.cannotDeleteOwnAccount',
    },
  },
  resetPassword: {
    title: 'resetPassword.title',
    newPasswordLabel: 'resetPassword.newPasswordLabel',
    submit: 'resetPassword.submit',
    invalidLink: 'resetPassword.invalidLink',
    success: 'resetPassword.success',
    error: 'resetPassword.error',
  },
  pagination: {
    previous: 'pagination.previous',
    next: 'pagination.next',
    pageOf: 'pagination.pageOf',
  },
} as const;
